version: '3.1'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_DB_HOST=db
      - JAVA_DB_USERNAME=root
      - JAVA_DB_PASSWORD=contraseña
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: contraseña
      MYSQL_DATABASE: nombre_db
    ports:
      - "3306:3306"
